Performing system checks...

System check identified no issues (0 silenced).
October 05, 2019 - 19:45:47
Django version 1.10.5, using settings 'ask.settings'
Starting development server at http://0.0.0.0:80/
Quit the server with CONTROL-C.
[05/Oct/2019 19:46:48] "GET / HTTP/1.1" 200 1
Not Found: /question/1
[05/Oct/2019 19:47:13] "GET /question/1 HTTP/1.1" 404 3014
Not Found: /question/1/
[05/Oct/2019 19:48:11] "GET /question/1/ HTTP/1.1" 404 3017
[05/Oct/2019 19:48:14] "GET / HTTP/1.1" 200 1
[05/Oct/2019 19:48:21] "GET /?page=1 HTTP/1.1" 200 1
[05/Oct/2019 19:49:15] "GET /?page=1 HTTP/1.1" 200 31
Performing system checks...

System check identified no issues (0 silenced).
October 05, 2019 - 19:46:37
Django version 1.10.5, using settings 'ask.settings'
Starting development server at http://0.0.0.0:80/
Quit the server with CONTROL-C.
[05/Oct/2019 19:50:48] "GET /?page=1 HTTP/1.1" 200 2
Performing system checks...

System check identified no issues (0 silenced).
October 05, 2019 - 19:50:39
Django version 1.10.5, using settings 'ask.settings'
Starting development server at http://0.0.0.0:80/
Quit the server with CONTROL-C.
[05/Oct/2019 19:51:57] "GET /?page=1 HTTP/1.1" 200 10
Performing system checks...

System check identified no issues (0 silenced).
October 05, 2019 - 19:51:33
Django version 1.10.5, using settings 'ask.settings'
Starting development server at http://0.0.0.0:80/
Quit the server with CONTROL-C.
[05/Oct/2019 19:54:20] "GET /?page=1 HTTP/1.1" 200 1
Performing system checks...

System check identified no issues (0 silenced).
October 05, 2019 - 19:52:33
Django version 1.10.5, using settings 'ask.settings'
Starting development server at http://0.0.0.0:80/
Quit the server with CONTROL-C.
Internal Server Error: /
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/exception.py", line 39, in inner
    response = get_response(request)
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/box/web/ask/qa/views.py", line 19, in page
    questions = paginator.get_page(page)
AttributeError: 'Paginator' object has no attribute 'get_page'
[05/Oct/2019 19:58:24] "GET /?page=1 HTTP/1.1" 500 59583
Internal Server Error: /
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/exception.py", line 39, in inner
    response = get_response(request)
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/box/web/ask/qa/views.py", line 19, in page
    questions = paginator.get_page(page)
AttributeError: 'Paginator' object has no attribute 'get_page'
[05/Oct/2019 19:59:08] "GET / HTTP/1.1" 500 59418
Internal Server Error: /
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/exception.py", line 39, in inner
    response = get_response(request)
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/box/web/ask/qa/views.py", line 19, in page
    questions = paginator.get_page(page)
AttributeError: 'Paginator' object has no attribute 'get_page'
[05/Oct/2019 20:00:22] "GET /?page=1 HTTP/1.1" 500 59583
Performing system checks...

System check identified no issues (0 silenced).
October 05, 2019 - 19:58:19
Django version 1.10.5, using settings 'ask.settings'
Starting development server at http://0.0.0.0:80/
Quit the server with CONTROL-C.
[05/Oct/2019 20:00:58] "GET /?page=1 HTTP/1.1" 200 66
[05/Oct/2019 20:01:17] "GET /?page=1 HTTP/1.1" 200 66
[05/Oct/2019 20:01:58] "GET /?page=1 HTTP/1.1" 200 66
[05/Oct/2019 20:02:09] "GET / HTTP/1.1" 200 66
[05/Oct/2019 20:02:18] "GET /?page=1 HTTP/1.1" 200 66
